var GAME_LEVELS = [
   ["                                                                                                                 ", 
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                    o                             x                               ",
   "                                                   xx   x                         x                               ",
   "                                             o  x!!xx  xx                         x                               ",
   "              oo                             x!!xxxxx   x                         x                               ",
   "       =      xx                          xx!xxxxxxxxx ox                         x                               ",
   "  @         xxxxxx       o               xxxxxxxxxxxx  xx                         x                               ",
   " xxxxx    xxxxxxxxxx     x    o   o      xxxx        o xx   =                     x                               ",
   " xxxxxxxxxxxxxxxxxxx!!!!!x!!!!x!!xxx!!xxxxxxx    o   x!xx      =                  x                               ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xx   xxxx               x     xooox                               ",
   " xxx                             oo         x    o      o             xxx     xxxxx                               ",
   " xxx          o                  oo         xx!!xx     xx o o o o   xxxxx     x   x                               ",
   " xxx     o    x                xxxxxx       xxxxxx!!!xxxx!x!x!x!x!xxxxxxx         x                               ",
   " xxx     x        o        xxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o      x                               ",
   " xxx         o    x       xxxxxxxxxxxxxx                                x!!x!!xx  x                               ", 
   " xxx         x        o   xxxxxxxxxxxxxxx       o!!                xx   xxxxxxxx  x                               ",
   " xxx                  x   xxxxxxxxxxxxxxxxxxxxxxxxxx!!!x o o o o o xx      o      x                               ",
   " xxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x!x!x!x!x!xxxxxxxxxxxxxxxx                               ",
   " xxx!!!!!!!!!!!!!!!!!!!!!xx                                                                                       ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",                                                                   
                                                                                                                      "],

  ["                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                         xx     =                                                            ",
   "                                         xx                                                                  ",
   "                                         xx                                                                  ",
   "                      o    oo            xx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "      o        o      x   xxx            xx          o   !!!!!!!!!!!!!      oo     xx                        ",
   "      x   xx   x   o         xo          xx       x                     oo         xx                        ",
   "                   x          xxo        xx           x  xxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "  x                             xxo      xx    !   o        x                                                ",
   "  xx o                            xx     xx  o        !xx   x                                                ",
   "  xx x                            xx     xx          o      x                                                ",
   "       o        o   o             xx     xx  !    !        xx                                                ",
   " xx!!!xx!xxx!!!!x!!!x!!x   x      xx     xx    o       !    x                                                ",
   " xxxxxxxxxxxxxxxxxxxxxxx          xx     xxxxxxxxxxxxxxxxx  x                                                ",
   " xxxxxxxxxxxxxxxxxxxxxxx     xx   xx           o            x                                                ",
   "                 xxxxxxx oo   x   xx       o      o         x                                                ",
   "          o            x xx   x   xx  o  xxxxxxxxxxxxxxxxxxxxx                                               ",
   "   o      x  xxxxxxxx  x      x   xx  x  xxx                                                                 ",
   "   x       o xxx    o  x   xx x            x                                                                 ",
   "       o   x xxx   xxxxxx     x!!!!!!!!!!!!x                                                                 ",
   "       x     xxx   x        xxxxxxxxxxxxxxxx                                                                 ",
   "         o   xxx  o       xx                                                                                 ",   
   "         x   xxxxxx     xxx                                                                                  ",
   "             xxx o     xx                                                                                    ",
   "     @    xxxxxxxxxxxxxxx                                                                                    ",
   "!!xxxxxxxxxxxxxxxxxxxxxxx                                                                                    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                     o                        ",
   "                                            o       o                                x                        ",
   "                        o                   x   x   x                            o                            ",
   "                        x   x   o       x              x                         x       x                    ",
   " xxxxxxxx         o  x          x     o                     o         o                    o                  ",
   "  @    o          x                   x                  x  x   x     x       x            x                  ",
   " xxxxxxxxx    x                                                                                               ",
   "           !!!!!!!!!!!!!!!!!!!!!!!!x                                                          xxxxxxxxx       ",
   "                                   !!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!        x     x ",
   "                                                       x                                               x    x ",
   "                                                       x                               o                    x ",
   "                                                       x           o                                       x  ",
   "                                                       x        xxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                      xxxxxxxxxxx     x!!!!!!!!!!x                            ",
   "                                                                x     xxxxxxxxxxxx                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                              ",
   "                                                                                                  x           ",
   "                                                                                                              ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o o.   x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                                                                ",
   "       x     x                                                x   x x   x x   x x   x x           x           ",
   "       x= o  x            x                                                                     x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  x                                                ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
